CREATE TABLE USERS(
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  FIRST_NAME VARCHAR(64) NOT NULL,
  LAST_NAME VARCHAR(64) NOT NULL,
  USERNAME VARCHAR(64) NOT NULL,
  USER_PASSWORD VARCHAR(64) NOT NULL,
  ADDRESS VARCHAR(64) NOT NULL,
  EMAIL VARCHAR(64),
  URL VARCHAR(64)
);

CREATE TABLE EVENTS(
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  USERS_ID BIGINT NOT NULL,
  EVENT_HOST VARCHAR(64),
  EVENT_TYPE VARCHAR(64),
  EVENT_TIME VARCHAR(64) NOT NULL,
  EVENT_DATE VARCHAR(64) NOT NULL,
  EVENT_ADDRESS VARCHAR(64) NOT NULL,
  DESCRIPTION VARCHAR(500) NOT NULL,
  NR_OF_GUESTS INT NOT NULL,
  PRICE INT NOT NULL,
  URL VARCHAR(64)
);

CREATE TABLE ATTENDEES(
ID BIGINT AUTO_INCREMENT PRIMARY KEY,
USERS_ID BIGINT NOT NULL,
EVENT_ID BIGINT NOT NULL
)